export {
  settingsActions,
  settingsGeneralSaveAction,
  settingsGeneralSetDefaultRegionAction,
  settingsGeneralSetNameAction,
  settingsImageDetailArchiveAction,
  settingsImageDetailBuildStartAction,
  settingsImageDetailBuildStopAction,
  settingsImageDetailCloneAction,
  settingsImageDetailDeleteAction,
  settingsImageDetailRevertAction,
  settingsImageDetailSaveAction,
  settingsImageDetailSetDescriptionAction,
  settingsImageDetailSetNameAction,
  settingsImagesOpenDetailAction,
} from "@/ui-actions/actions/settings";
