[unix_http_server]
file=%(ENV_ROOT_DIR)s/supervisor/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=%(ENV_ROOT_DIR)s/logs/supervisord.log
logfile_maxbytes=0
pidfile=%(ENV_ROOT_DIR)s/supervisor/supervisord.pid
childlogdir=%(ENV_ROOT_DIR)s/logs

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://%(ENV_ROOT_DIR)s/supervisor/supervisor.sock

[program:main]
command=/bin/bash -lc 'exec %(ENV_AGENT_START_COMMAND)s'
autostart=true
autorestart=true
startsecs=1
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:openvscode-server]
command=%(ENV_AGENT_DOCKER_DIR)s/runit/openvscode-server.sh
autostart=true
autorestart=unexpected
exitcodes=0
startsecs=1
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:openvscode-proxy]
command=%(ENV_AGENT_DOCKER_DIR)s/runit/openvscode-proxy.sh
autostart=true
autorestart=unexpected
exitcodes=0
startsecs=1
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:ui-stack]
command=%(ENV_AGENT_DOCKER_DIR)s/runit/ui-stack.sh
autostart=true
autorestart=unexpected
exitcodes=0
startsecs=1
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:dockerd]
command=%(ENV_AGENT_DOCKER_DIR)s/runit/dockerd.sh
autostart=true
autorestart=unexpected
exitcodes=0
startsecs=1
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
